### ISSUE TITLE
Security

### ISSUE THREAD

**Issue by mb21** [pkozlowski-opensource/angularjs-mongolab#10]
Am I missing something or do I have to put my mongolab API key into the javascript that gets shipped to my users browsers?

**Comment by pkozlowski-opensource** [comment]
@mb21 no, you are not missing anything, it is how MongLab operates today, see:
https://support.mongolab.com/entries/20269612-REST-api-permissions-and-security-best-practice
https://support.mongolab.com/entries/20433053-REST-API-for-MongoDB

Sending apiKey with each request is not a big deal if you are not concerned with data security (that is, you are operating on public, easy to recover data, demo data etc.). As soon as you start to have security concerns you have to proxy requests to the MongoLab REST API through the server. This is why the `BASE_URL` config option is provided so you can hit your own server instead of MongoLab servers directly.

I would be happy to extend the wrapper as soon as MongoLab provides other options of securing requests but there is not much I can do at the moment so closing this issue.
