### ISSUE TITLE
Error on save when pushing into array

### ISSUE THREAD

**Issue by sonicparke** [pkozlowski-opensource/angularjs-mongolab#11]
I have a need to take data entered into the form and do calculations on it then push the result into the model as well as the original values. The problem I'm having is that I get an error when trying to save or saveOrUpdate to my mongolab db. It appears that if I mess with the model it removes all the methods you've created. Can what I need to do be done with this or will I need to dig into the MongoLab API and go server-side from the beginning?

To demonstrate I'm taking the Name & Site and concatenating them and pushing the result into the model: http://plnkr.co/edit/mfS046?p=preview

Great resource though. I like it!

**Comment by pkozlowski-opensource** [comment]
@sonicparke sorry for the veeeeerrrryyy late replay, wasn't paying enough attention to issues in this project :-/

Coming back to your problem - the issue is that you are re-creating the whole `project` object here:

``` javascript
$scope.project = {
        nameSite: $scope.nameSite
    };
```

thus dropping all the methods that are defined on a resource prototype (`$save`, `$update` etc.). What you should be doing instead is to simply update / define a property on the existing resource object:

``` javascript
$scope.project.nameSite = $scope.nameSite;
```
